neo4j_bin: '<TO_FILL>'
neo4j_data: '<TO_FILL>'
neo4j_report: '<TO_FILL>'

db_dst:
  uri: '<TO_FILL>'
  user: '<TO_FILL>'
  password: '<TO_FILL>'

csv_dst:
  node: '<TO_FILL>'
  link: '<TO_FILL>'

data_src:
  component : '<TO_FILL>'
  kanji : '<TO_FILL>'
  radical : '<TO_FILL>'
  word : '<TO_FILL>'



